#!/bin/bash
# journey-map-sentinel-gate.sh — protects the journey map from hand-rolled /
#                                sentinel-stripping writes.
#
# Hook    : PreToolUse:Write|Edit
# Mode    : DENY
# State   : none (shape-only, reads the proposed content)
# Env     : HEKTOR_JOURNEYMAP_GATE=off   advisory bypass
#
# Why
# ---
# docs/hektor/journey-map.md is the blueprint hektor-test-composer and
# hektor-coverage-expansion consume. Its line 1 must be the sentinel
# `<!-- hektor:journey-mapping -->`, the machine-readable signal that the file
# was produced by hektor-journey-mapping rather than improvised in orchestrator
# context. This gate denies any write whose proposed line 1 isn't that sentinel:
# the first write must carry it, and an edit that strips it is denied. Edits that
# keep the sentinel on line 1 pass untouched.
#
# Port of Achilles' journey-map-sentinel-gate.sh, retargeted to Hektor's path +
# sentinel. Uses the same literal index()-based Edit reconstruction as
# run-status-write-gate (NOT awk sub(), which is ERE and can fail open).
set -uo pipefail

_LIB="$(dirname "${BASH_SOURCE[0]}")/lib/audit.sh"
if [ -f "$_LIB" ]; then . "$_LIB"; else hektor_audit() { :; }; fi

if [ "${HEKTOR_JOURNEYMAP_GATE:-on}" = "off" ]; then
  hektor_audit "journey-map-sentinel-gate bypassed (HEKTOR_JOURNEYMAP_GATE=off)"
  exit 0
fi

JQ="$(command -v jq || true)"
[ -n "$JQ" ] || exit 0

SENTINEL="<!-- hektor:journey-mapping -->"

INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | "$JQ" -r '.tool_name // empty' 2>/dev/null || echo "")
case "$TOOL_NAME" in Write|Edit) ;; *) exit 0 ;; esac

TARGET=$(echo "$INPUT" | "$JQ" -r '.tool_input.file_path // empty' 2>/dev/null || echo "")
case "$TARGET" in
  */docs/hektor/journey-map.md) ;;
  *) exit 0 ;;
esac

# Reconstruct proposed content.
PROPOSED=""
case "$TOOL_NAME" in
  Write)
    PROPOSED=$(echo "$INPUT" | "$JQ" -r '.tool_input.content // empty' 2>/dev/null || echo "")
    ;;
  Edit)
    OLD=$(echo "$INPUT" | "$JQ" -r '.tool_input.old_string // empty' 2>/dev/null || echo "")
    if [ -f "$TARGET" ] && [ -n "$OLD" ]; then
      NEW=$(echo "$INPUT" | "$JQ" -r '.tool_input.new_string // empty' 2>/dev/null || echo "")
      PROPOSED=$(awk -v o="$OLD" -v n="$NEW" '
        BEGIN { RS="\0" }
        {
          rest=$0; out="";
          if (o == "") { printf "%s", rest; next }
          while ((p=index(rest,o)) > 0) {
            out = out substr(rest,1,p-1) n;
            rest = substr(rest, p+length(o));
          }
          printf "%s", out rest;
        }
      ' "$TARGET" 2>/dev/null || echo "")
    fi
    ;;
esac
[ -n "$PROPOSED" ] || exit 0

LINE1=$(printf '%s\n' "$PROPOSED" | head -1)
# Trim trailing CR/space.
LINE1="${LINE1%$'\r'}"
[ "$LINE1" = "$SENTINEL" ] && exit 0

"$JQ" -n --arg r "[BLOCKED — Hektor journey-map-sentinel-gate] journey-map.md line 1 must be the sentinel.

Target:   ${TARGET}
Line 1:   \"${LINE1}\"
Expected: \"${SENTINEL}\"

docs/hektor/journey-map.md is the blueprint the composer + coverage-expansion
skills read. Its first line must be the sentinel that marks it as generated by
hektor-journey-mapping — not hand-rolled or improvised in orchestrator context.
This write would create or leave the map without that marker.

Fix: produce the map via the hektor-journey-mapping skill (it writes the
sentinel as line 1), or keep the sentinel intact when editing.

Bypass (audit the use): HEKTOR_JOURNEYMAP_GATE=off." '{
  "hookSpecificOutput": {
    "hookEventName": "PreToolUse",
    "permissionDecision": "deny",
    "permissionDecisionReason": $r
  }
}'
exit 0
