import type { Finding, FindingSeverity, PhaseState, TestArtifact } from '../types';
import { EmptyState } from './FindingsTab';
import { phaseWaitState } from '../consoleAlerts';

interface Props {
  reportUrl: string | null;
  reportReady: boolean;        // Phase 8 done?
  reportIsReal: boolean;       // true when reportUrl points at a real served deck (/api/...)
  tests: TestArtifact[];
  findings: Finding[];
  filesCount: number;
  elapsedMs: number;
  /** Phase state for `report` — sharpens the not-ready copy. */
  phase?: PhaseState;
}

/**
 * When the run is backed by the real engine, reportUrl points at an
 * actual qa-summary-deck.html served by the server — iframe it directly.
 * The simulator only sets a symbolic reportUrl (no HTML file on disk), so
 * in that case — or whenever reportIsReal is false — we fall back to a
 * stylized in-app preview that mirrors what the real deck shows: counts,
 * severity breakdown, top tests.
 */
export function ReportTab({
  reportUrl,
  reportReady,
  reportIsReal,
  tests,
  findings,
  filesCount,
  elapsedMs,
  phase,
}: Props) {
  if (reportReady && reportIsReal && reportUrl) {
    return (
      <div className="report-tab report-tab-real">
        <div className="report-real-bar">
          <span className="dim">qa-summary-deck.html</span>
          <a className="report-open" href={reportUrl} target="_blank" rel="noreferrer">open ↗</a>
        </div>
        <iframe className="report-frame" title="QA summary deck" src={reportUrl} />
      </div>
    );
  }

  if (!reportReady) {
    const wait = phaseWaitState(phase);
    if (wait === 'running') {
      return (
        <EmptyState
          glyph="◷"
          tone="waiting"
          title="Generating the report"
          body="Phase VIII is assembling the QA summary deck now — this view updates automatically the moment it's done."
        />
      );
    }
    if (wait === 'settled') {
      return (
        <EmptyState
          glyph="◷"
          title="Report phase didn't complete"
          body="Phase VIII ended without producing a deck. Check the Log tab for what happened."
        />
      );
    }
    return (
      <EmptyState
        glyph="◷"
        tone="waiting"
        title="Report not ready yet"
        body="The QA summary deck is generated by Phase VIII. It appears here automatically the moment the report phase completes — no need to refresh."
      />
    );
  }

  const sevCounts = findings.reduce(
    (acc, f) => {
      acc[f.severity] += 1;
      return acc;
    },
    { critical: 0, high: 0, medium: 0, low: 0, info: 0 } as Record<FindingSeverity, number>
  );
  const elapsedLabel = formatLongDuration(elapsedMs);

  return (
    <div className="report-tab">
      <div className="report-deck">
        <div className="report-deck-head">
          <div className="report-eyebrow">QA SUMMARY DECK · v0.1</div>
          <div className="report-headline">
            <span className="report-headline-mark">Λ</span>
            <span className="report-headline-text">
              hektor delivered an end-to-end suite.
            </span>
          </div>
          <div className="report-deckline">
            <span>{elapsedLabel}</span>
            <span className="dot">·</span>
            <span>8 phases</span>
            <span className="dot">·</span>
            <span>{tests.length} tests</span>
            <span className="dot">·</span>
            <span>{findings.length} findings</span>
          </div>
        </div>

        <div className="report-grid">
          <ReportStat label="Tests written" value={String(tests.length)} sub={`${tests.length} live in suite`} accent="accent" />
          <ReportStat label="Files touched" value={String(filesCount)} sub="config, fixtures, specs, docs" />
          <ReportStat label="Findings" value={String(findings.length)} sub={`${sevCounts.critical} crit / ${sevCounts.high} high`} accent={findings.length > 0 ? 'warn' : 'neutral'} />
          <ReportStat label="Wall clock" value={elapsedLabel} sub="end to end" />
        </div>

        <div className="report-section">
          <div className="report-section-head">Severity breakdown</div>
          <div className="report-sev-bar">
            <SevSeg n={sevCounts.critical} total={findings.length || 1} className="sev-critical" label="crit" />
            <SevSeg n={sevCounts.high} total={findings.length || 1} className="sev-high" label="high" />
            <SevSeg n={sevCounts.medium} total={findings.length || 1} className="sev-medium" label="med" />
            <SevSeg n={sevCounts.low} total={findings.length || 1} className="sev-low" label="low" />
          </div>
        </div>

        {tests.length > 0 && (
          <div className="report-section">
            <div className="report-section-head">Sample tests</div>
            <ul className="report-tests">
              {tests.slice(0, 6).map((t) => (
                <li key={t.id}>
                  <span className="report-tests-bullet">▸</span>
                  <span className="report-tests-name">{t.name}</span>
                </li>
              ))}
              {tests.length > 6 && (
                <li className="report-tests-more">… +{tests.length - 6} more</li>
              )}
            </ul>
          </div>
        )}

        <div className="report-footer">
          {reportUrl ? (
            <span className="report-footer-path">
              <span className="dim">written to</span>{' '}
              <code>{reportUrl}</code>
            </span>
          ) : (
            <span className="dim">in-app preview · no deck file on disk</span>
          )}
        </div>
      </div>
    </div>
  );
}

function ReportStat({
  label,
  value,
  sub,
  accent,
}: {
  label: string;
  value: string;
  sub: string;
  accent?: 'accent' | 'warn' | 'neutral';
}) {
  return (
    <div className={`report-stat accent-${accent ?? 'neutral'}`}>
      <div className="report-stat-label">{label}</div>
      <div className="report-stat-value">{value}</div>
      <div className="report-stat-sub">{sub}</div>
    </div>
  );
}

function SevSeg({ n, total, className, label }: { n: number; total: number; className: string; label: string }) {
  const pct = total === 0 ? 0 : Math.round((n / total) * 100);
  if (n === 0) return null;
  return (
    <div className={`sev-seg ${className}`} style={{ width: `${pct}%` }} title={`${label}: ${n}`}>
      <span className="sev-seg-num">{n}</span>
      <span className="sev-seg-label">{label}</span>
    </div>
  );
}

function formatLongDuration(ms: number): string {
  if (ms <= 0) return '0s';
  const total = Math.round(ms / 1000);
  const m = Math.floor(total / 60);
  const s = total % 60;
  if (m === 0) return `${s}s`;
  return `${m}m ${String(s).padStart(2, '0')}s`;
}
