#!/bin/bash
# journey-map-sentinel-gate.sh — protects the journey map from hand-rolled /
#                                sentinel-stripping writes.
#
# Event   : preToolUse  (any write-shaped tool call)
# Mode    : DENY
# State   : none (shape-only, reads the proposed content)
# Env     : HEKTOR_JOURNEYMAP_GATE=off   advisory bypass
#
# Why
# ---
# docs/hektor/journey-map.md is the blueprint hektor-test-composer and
# hektor-coverage-expansion consume. Its line 1 must be the sentinel
# `<!-- hektor:journey-mapping -->`, the machine-readable signal that the file
# was produced by hektor-journey-mapping rather than improvised in orchestrator
# context. This gate denies any write whose proposed line 1 isn't that sentinel:
# the first write must carry it, and an edit that strips it is denied. Edits that
# keep the sentinel on line 1 pass untouched.
#
# Port of Achilles' journey-map-sentinel-gate.sh, retargeted to Hektor's path +
# sentinel. Uses the same literal index()-based Edit reconstruction as
# run-status-write-gate (NOT awk sub(), which is ERE and can fail open).
set -uo pipefail

_DIR="$(dirname "${BASH_SOURCE[0]}")"
[ -f "$_DIR/lib/audit.sh" ]        && . "$_DIR/lib/audit.sh"        || hektor_audit() { :; }
[ -f "$_DIR/lib/hook_profile.sh" ] && . "$_DIR/lib/hook_profile.sh" || hektor_hook_enabled() { return 0; }
[ -f "$_DIR/lib/cursor.sh" ]       && . "$_DIR/lib/cursor.sh"       || exit 0

[ "${HEKTOR_JOURNEYMAP_GATE:-on}" = "off" ] && { hektor_audit "journey-map-sentinel-gate bypassed (HEKTOR_JOURNEYMAP_GATE=off)"; exit 0; }
hektor_gate_init journey-map-sentinel-gate "standard,strict"

SENTINEL="<!-- hektor:journey-mapping -->"

TARGET="$(hektor_file_path)"
case "$TARGET" in
  */docs/hektor/journey-map.md) ;;
  *) exit 0 ;;
esac

# Reconstruct the proposed content. A whole-file write is already it; a partial
# edit is replayed against disk with a literal index() replace (NOT awk sub(),
# which is ERE and can fail open on a regex-special old_string).
PROPOSED=""
OLD="$(hektor_old_string)"
if [ -z "$OLD" ]; then
  PROPOSED="$(hektor_added_text)"
elif [ -f "$TARGET" ]; then
  NEW="$(hektor_new_string)"
  PROPOSED=$(_o="$OLD" _n="$NEW" awk '
    BEGIN { RS="\0"; o=ENVIRON["_o"]; n=ENVIRON["_n"] }
    {
      rest=$0; out="";
      if (o == "") { printf "%s", rest; next }
      while ((p=index(rest,o)) > 0) {
        out = out substr(rest,1,p-1) n;
        rest = substr(rest, p+length(o));
      }
      printf "%s", out rest;
    }
  ' "$TARGET" 2>/dev/null || echo "")
fi
[ -n "$PROPOSED" ] || exit 0

LINE1=$(printf '%s\n' "$PROPOSED" | head -1)
# Trim trailing CR/space.
LINE1="${LINE1%$'\r'}"
[ "$LINE1" = "$SENTINEL" ] && exit 0

hektor_deny "[BLOCKED — Hektor journey-map-sentinel-gate] journey-map.md line 1 must be the sentinel.

Target:   ${TARGET}
Line 1:   \"${LINE1}\"
Expected: \"${SENTINEL}\"

docs/hektor/journey-map.md is the blueprint the composer + coverage-expansion
skills read. Its first line must be the sentinel that marks it as generated by
hektor-journey-mapping — not hand-rolled or improvised in orchestrator context.
This write would create or leave the map without that marker.

Fix: produce the map via the hektor-journey-mapping skill (it writes the
sentinel as line 1), or keep the sentinel intact when editing.

Bypass (audit the use): HEKTOR_JOURNEYMAP_GATE=off."
exit 0
